FROM python:3.12.5-alpine AS backend

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1 
ENV INSTANCE_CHANGELOG_URL https://sites.plane.so/pages/691ef037bcfe416a902e48cb55f59891/

ARG APK_REPOSITORY_HOST=dl-cdn.alpinelinux.org
ARG PIP_INDEX_URL=https://pypi.org/simple

RUN sed -i "s#dl-cdn.alpinelinux.org#${APK_REPOSITORY_HOST}#g" /etc/apk/repositories && \
    apk --no-cache add \
    "bash~=5.2" \
    "libpq" \
    "libxslt" \
    "nodejs-current" \
    "xmlsec" \
    "libffi-dev" \
    "bash~=5.2" \
    "g++" \
    "gcc" \
    "cargo" \
    "git" \
    "make" \
    "postgresql-dev" \
    "libc-dev" \
    "linux-headers"

WORKDIR /code

COPY requirements.txt ./requirements.txt
ADD requirements ./requirements

# Install the local development settings
RUN pip install --index-url "${PIP_INDEX_URL}" -r requirements/local.txt --compile --no-cache-dir


COPY . .

RUN mkdir -p /code/plane/logs
RUN chmod -R +x /code/bin
RUN chmod -R 777 /code


# Expose container port and run entry point script
EXPOSE 8000

CMD [ "./bin/docker-entrypoint-api-local.sh" ]

